<a href="https://colab.research.google.com/github/premsatpute/ml_basics/blob/main/labelEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('customer.csv')

In [ ]:
df.sample(5)

age  gender   review education purchased
33   89  Female     Good        PG       Yes
10   98  Female     Good        UG       Yes
9    74    Male     Good        UG       Yes
48   39  Female     Good        UG       Yes
30   73    Male  Average        UG        No

In [10]:
# finding count of categories in a column
for i in df.iloc[:,1:].columns:
  print(df[i].value_counts())

gender
Female    29
Male      21
Name: count, dtype: int64
review
Poor       18
Good       18
Average    14
Name: count, dtype: int64
education
PG        18
School    16
UG        16
Name: count, dtype: int64
purchased
No     26
Yes    24
Name: count, dtype: int64


In [12]:
df = df.iloc[:,2:]

In [13]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [14]:
from sklearn.model_selection import train_test_split


In [15]:
X_train , X_test,Y_train, Y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [16]:
from sklearn.preprocessing import OrdinalEncoder

In [17]:
X_train.head()

review education
46     Poor        PG
37  Average        PG
7      Poor    School
40     Good    School
11     Good        UG

In [19]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [24]:
k=oe.fit(X_train)

In [25]:
X_train = oe.transform(X_train)

In [26]:
X_train

array([[0., 1.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [1., 1.],
       [0., 0.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [1., 0.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [2., 0.],
       [0., 0.],
       [0., 1.],
       [2., 2.],
       [0., 1.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [1., 2.],
       [2., 1.],
       [1., 1.],
       [0., 0.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [1., 1.],
       [1., 2.],
       [0., 1.],
       [1., 2.],
       [1., 1.],
       [1., 0.]])

In [27]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [ ]:
X_train

array([[1., 2.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [0., 0.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [2., 2.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [1., 2.],
       [2., 1.],
       [1., 0.],
       [2., 0.]])

In [28]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
le.fit(y_train)

LabelEncoder()

In [ ]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [ ]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [ ]:
y_train

array([1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1])